//! `r14n extract` — catalog → pack TEMPLATE (the i18n "extract keys" analogue).
//!
//! The generated template is FAIL-CLOSED: the floor defaults to EVERY catalog
//! control; counsel prunes downward, never fills upward from empty. The
//! template is a draft (`legal_review.status = "draft"`) and carries the
//! NOT-LEGAL-ADVICE header. Field naming per spec §2.5 (wire `strictness`).
//!
//! Revision History
//! - 2026-07-06: authored — roadmap item 5 (pack-lifecycle CLI).

/// Render a pack template for `profile` from a loaded catalog.
pub fn template(catalog: &crate::catalog::Catalog, profile: &str) -> ::std::string::String {
  let mut out = ::std::string::String::new();
  out.push_str("# SPDX-License-Identifier: CC-BY-4.0\n");
  out.push_str(&::std::format!(
    "# RLPS pack TEMPLATE — domain: {} — profile: {}\n",
    catalog.domain, profile
  ));
  out.push_str("# Generated by `r14n extract`. NOT LEGAL ADVICE — this template is a draft of\n");
  out.push_str("# controls, not a statement of any jurisdiction's law. A pack claiming a real\n");
  out.push_str("# jurisdiction MUST be reviewed and attested by licensed counsel (spec §6).\n");
  out.push_str("#\n# Catalog controls (reference these keys; do not invent new ones here):\n");
  for (key, def) in &catalog.controls {
    out.push_str(&::std::format!("#   {key}  ({})  — {}\n", def.kind, def.title));
  }
  out.push_str("\n[meta]\nstrictness = \"as_configured\"\n");
  out.push_str(&::std::format!(
    "description = \"TODO — {} controls for profile {}\"\n",
    catalog.domain, profile
  ));
  out.push_str("effective_from = \"TODO-YYYY-MM-DD\"\n");
  out.push_str("last_reviewed_against_guidance = \"TODO-YYYY-MM-DD\"\n");
  out.push_str("\n[meta.legal_review]\nstatus = \"draft\"\n");
  out.push_str("# For a real jurisdiction, counsel review makes these REQUIRED (spec §6):\n");
  out.push_str("# reviewing_attorney_of_record = \"\"\n# jurisdiction = \"\"\n");
  out.push_str("# bar_credential = \"\"\n# review_date = \"YYYY-MM-DD\"\n");
  out.push_str("\n# One table per subject; delete the example and fill per counsel:\n");
  out.push_str("# [subject.<name>]\n# controls = []\n");
  out.push_str("\n# FAIL-CLOSED default floor: every catalog control. Prune with counsel —\n");
  out.push_str("# never publish an empty floor (a missing floor blocks, spec §4).\n");
  out.push_str("[legally_required]\ncontrols = [\n");
  for key in catalog.controls.keys() {
    out.push_str(&::std::format!("  \"{key}\",\n"));
  }
  out.push_str("]\n");
  out.push_str("\n# Controls this profile FORBIDS (data-minimization guard input, spec §3):\n");
  out.push_str("# [prohibited]\n# controls = []\n");
  out
}

#[cfg(test)]
mod tests {
  #[test]
  fn template_is_fail_closed_and_draft() {
    let tmp = ::tempfile::tempdir().expect("tmp");
    let path = tmp.path().join("c.toml");
    ::std::fs::write(&path, crate::catalog::TEST_CATALOG).expect("write");
    let cat = crate::catalog::load(&path).expect("load");
    let t = super::template(&cat, "example_profile");
    ::std::assert!(t.contains("NOT LEGAL ADVICE"));
    ::std::assert!(t.contains("status = \"draft\""));
    // Floor lists every catalog control (fail-closed default).
    for key in ["attestation", "signal_notice", "aph_mandate"] {
      ::std::assert!(t.contains(&::std::format!("  \"{key}\",")), "floor missing {key}");
    }
    // The template itself must be valid TOML.
    let parsed: ::std::result::Result<::toml::Value, _> = ::toml::from_str(&t);
    ::std::assert!(parsed.is_ok(), "template must parse as TOML: {parsed:?}");
  }
}
