// SPDX-License-Identifier: Apache-2.0
//! Golden-file guard for the worked AI-Act §50 example (council-audit E4).
//!
//! The checked-in `docs/examples/receipt-ai-act-50.json` is generated by
//! `cargo run --example ai_act_50`. It drifts silently if the receipt format
//! changes but the file is not regenerated. This test rebuilds the example
//! receipt from the SAME inputs and asserts it matches the checked-in file
//! byte-for-byte — so either the file is regenerated or this fails.
//!
//! Revision History
//! - 2026-07-07: authored — council-audit E4 (doc-example regeneration guard).

/// Rebuild the exact receipt document the `ai_act_50` example emits. Keep this
/// in lockstep with `resolver/examples/ai_act_50.rs`.
fn rebuild_example() -> ::std::string::String {
  let universe: ::std::collections::BTreeSet<::r14n::ControlKey> = [
    "attestation", "signal_notice", "indicator_mount", "announcement", "aph_mandate", "ai_disclosure",
  ]
  .into_iter()
  .map(|s| ::r14n::ControlKey(::std::string::String::from(s)))
  .collect();
  let query = ::r14n::RegulatoryQuery {
    domain: ::std::string::String::from("recording_consent"),
    profile: ::r14n::RegulatoryProfile(::std::string::String::from("aggressive")),
    jurisdiction: ::std::string::String::from("all_party"),
    subject: ::std::string::String::from("twin_attend"),
    universe,
    as_of: ::std::option::Option::None,
  };
  let adapter = ::r14n::AggressiveDefaultPolicyAdapter;
  let decision = ::r14n::RegulatoryPolicyPort::required_controls(&adapter, &query);
  let ctx = ::r14n::receipt::ReceiptContext {
    record_id: ::std::string::String::from("urn:rlps:receipt:example:ai-act-50"),
    issued_at: ::std::string::String::from("2026-08-02T09:00:00Z"),
    issued_at_unix: 1_785_661_200,
    language: ::std::string::String::from("de"),
    pii_principal_id: ::std::string::String::from("participant:example"),
    pii_controller: ::std::string::String::from("Example Operator GmbH"),
    policy_url: ::std::option::Option::Some(::std::string::String::from("https://example.invalid/privacy")),
    domain: ::std::string::String::from("recording_consent"),
    subject: ::std::string::String::from("twin_attend"),
    operations: ::std::vec![
      ::std::string::String::from("rlps:AudioRecording"),
      ::std::string::String::from("rlps:VoiceRecording"),
    ],
    jurisdictions: ::std::vec![::std::string::String::from("DE")],
    attribution_source: ::std::string::String::from("operator_declared"),
    gpc_signal: false,
    ieee7012_no_recording: false,
    sensitive: true,
    spi_cat: ::std::vec![::std::string::String::from("rlps:VoiceRecording")],
    ai_disclosure: ::std::option::Option::Some(::r14n::receipt::AiDisclosure {
      disclosed_at: ::std::string::String::from("2026-08-02T08:59:00Z"),
      method: ::std::string::String::from("in_meeting_announcement"),
    }),
    pack_sha256: ::std::option::Option::None,
  };
  let dpv: ::serde_json::Value =
    ::serde_json::from_str(&::r14n::receipt::dpv_27560_json(&decision, &ctx)).expect("dpv json");
  let kantara: ::serde_json::Value =
    ::serde_json::from_str(&::r14n::receipt::kantara_cr_v1_1_json(&decision, &ctx)).expect("kantara json");
  let combined = ::serde_json::json!({ "dpv_27560": dpv, "kantara_cr_v1_1": kantara });
  ::serde_json::to_string_pretty(&combined).expect("serialize")
}

/// Why: the checked-in receipt example is documentation integrators copy; if the
/// receipt format changes and the file is not regenerated, the docs lie. This
/// pins the file to the current serializer output (regenerate with
/// `cargo run --example ai_act_50 > docs/examples/receipt-ai-act-50.json`).
#[test]
fn checked_in_example_receipt_matches_current_serializer() {
  let path = ::std::path::Path::new(::std::env!("CARGO_MANIFEST_DIR"))
    .join("..")
    .join("docs/examples/receipt-ai-act-50.json");
  let on_disk = ::std::fs::read_to_string(&path).expect("read example");
  ::std::assert_eq!(
    on_disk.trim_end(),
    rebuild_example().trim_end(),
    "docs/examples/receipt-ai-act-50.json is STALE — regenerate: cargo run --example ai_act_50 > docs/examples/receipt-ai-act-50.json"
  );
}
